# Generated by Django 3.0.3 on 2020-02-18 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=50, null=True)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('password1', models.CharField(blank=True, max_length=50, null=True)),
                ('password2', models.CharField(blank=True, max_length=50, null=True)),
                ('mobile', models.IntegerField(blank=True, max_length=12, null=True)),
            ],
        ),
    ]
