# Generated by Django 3.0.3 on 2020-02-18 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='mobile',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
