# Generated by Django 3.0.3 on 2020-02-20 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_driver'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='license',
            new_name='license_no',
        ),
        migrations.RenameField(
            model_name='driver',
            old_name='ownership',
            new_name='ownership_no',
        ),
    ]
