# Generated by Django 3.0.3 on 2020-02-20 13:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200220_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driver',
            name='update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='license_no',
            field=models.ImageField(upload_to='media/license'),
        ),
    ]
